# Bloc King Kusaila à coller dans ~/.config/hypr/userprefs.conf

# King Kusaila voice layer
# Super+V = mission vocale -> demande background/terminal puis lance King Kusaila
unbind = SUPER, C
unbind = SUPER, V
bind = SUPER, C, exec, /home/kusaila/.local/bin/voice-dictate-toggle
bind = SUPER, V, exec, /home/kusaila/.local/bin/king-kusaila-toggle
exec-once = /home/kusaila/.local/bin/king-kusaila-visual --daemon-start
windowrule = float true, match:title ^(King Kusaila Visual)$
windowrule = pin true, match:title ^(King Kusaila Visual)$
windowrule = decorate false, match:title ^(King Kusaila Visual)$
windowrule = border_size 0, match:title ^(King Kusaila Visual)$
windowrule = rounding 0, match:title ^(King Kusaila Visual)$
windowrule = opacity 1.0 1.0, match:title ^(King Kusaila Visual)$
windowrule = no_blur true, match:title ^(King Kusaila Visual)$
windowrule = float true, match:title ^(King Kusaila Choice)$
windowrule = pin true, match:title ^(King Kusaila Choice)$
windowrule = decorate false, match:title ^(King Kusaila Choice)$
windowrule = border_size 0, match:title ^(King Kusaila Choice)$
windowrule = rounding 0, match:title ^(King Kusaila Choice)$
windowrule = opacity 1.0 1.0, match:title ^(King Kusaila Choice)$
windowrule = no_blur true, match:title ^(King Kusaila Choice)$
