$font = Adwaita Sans
$glyph = JetBrainsMono Nerd Font

$blanc = rgba(ffffffff)
$doux = rgba(ffffffb3)
$faible = rgba(ffffff70)
$verre = rgba(16181ea8)
$trait = rgba(ffffff26)
$ko = rgba(f7768eff)

general {
    hide_cursor = true
    grace = 0
    no_fade_in = false
    no_fade_out = true
    disable_loading_bar = true
    ignore_empty_input = true
    immediate_render = true
}

auth {
    fingerprint {
        enabled = true
        ready_message = Pose ton doigt
        present_message = Lecture du doigt
        retry_delay = 300
    }
}

background {
    monitor =
    path = $BACKGROUND_PATH
    blur_passes = 3
    blur_size = 7
    brightness = 0.32
    contrast = 0.95
    vibrancy = 0.12
    noise = 0.012
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = $blanc
    font_size = 150
    font_family = $font
    position = 0, 230
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] LC_TIME=fr_FR.utf8 date +"%A %-d %B"
    color = $faible
    font_size = 22
    font_family = $font
    position = 0, 128
    halign = center
    valign = center
}

shape {
    monitor =
    size = 190, 190
    color = $verre
    rounding = 95
    border_size = 1
    border_color = $trait
    position = 0, -60
    halign = center
    valign = center
}

label {
    monitor =
    text = 󰈷
    color = $doux
    font_size = 84
    font_family = $glyph
    position = 0, -60
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 440, 64
    outline_thickness = 1
    dots_size = 0.24
    dots_spacing = 0.42
    dots_center = true
    dots_rounding = -1
    outer_color = $trait
    inner_color = $verre
    font_color = $blanc
    font_family = $font
    check_color = $doux
    fail_color = $ko
    capslock_color = $ko
    fade_on_empty = false
    rounding = 32
    placeholder_text = <span foreground="##ffffffb3">$FPRINTPROMPT</span>
    fail_text = <span foreground="##f7768eff">$FAIL</span>
    hide_input = false
    position = 0, -224
    halign = center
    valign = center
}

label {
    monitor =
    text = ou tape ton mot de passe
    color = $faible
    font_size = 15
    font_family = $font
    position = 0, -296
    halign = center
    valign = center
}
